# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hreysi < Formula
  desc "Ambient buildlog capture — every commit, journaled."
  homepage "https://github.com/Peleke/hreysi"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.3/hreysi_0.1.3_darwin_amd64.tar.gz"
      sha256 "d25651ee215b5a067508f6d1b3d6417c63a478ef5592f0ace6d4ebbfb4a4bcbc"

      define_method(:install) do
        bin.install "hreysi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.3/hreysi_0.1.3_darwin_arm64.tar.gz"
      sha256 "7764ab6f480d6dbb4d1da0e49179b6d3e92d26625525380010922eb069117ff9"

      define_method(:install) do
        bin.install "hreysi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.3/hreysi_0.1.3_linux_amd64.tar.gz"
      sha256 "e952694be37428292d63092268a71cd4d5c6bdb3df65b7ba973b1f7930e96805"
      define_method(:install) do
        bin.install "hreysi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.3/hreysi_0.1.3_linux_arm64.tar.gz"
      sha256 "9aae0d3b41cf28b17d67ef39deb9d708d30b325c409b27921f9c00295b0b6aa5"
      define_method(:install) do
        bin.install "hreysi"
      end
    end
  end

  test do
    system "#{bin}/hreysi", "version"
  end
end
