# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hreysi < Formula
  desc "Ambient buildlog capture — every commit, journaled."
  homepage "https://github.com/Peleke/hreysi"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.4/hreysi_0.1.4_darwin_amd64.tar.gz"
      sha256 "c6469aa93fbbc90b0e451e1924978091be4e715ce3e8f1878617051ec64f68df"

      define_method(:install) do
        bin.install "hreysi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.4/hreysi_0.1.4_darwin_arm64.tar.gz"
      sha256 "8fdef3ff8a873096ae752be5993e84b6b1a74924fa043988b855c5378e3a4242"

      define_method(:install) do
        bin.install "hreysi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.4/hreysi_0.1.4_linux_amd64.tar.gz"
      sha256 "f412f986360fbaf6081a723063236755d4dba0f3168bf1d70b751f788fe33dde"
      define_method(:install) do
        bin.install "hreysi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Peleke/hreysi/releases/download/v0.1.4/hreysi_0.1.4_linux_arm64.tar.gz"
      sha256 "e56caee50c81069c7ca2e5492a8cea1b23884bf8ff3bb2c8bef5dc8f38a27ef0"
      define_method(:install) do
        bin.install "hreysi"
      end
    end
  end

  test do
    system "#{bin}/hreysi", "version"
  end
end
